dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
script: bash build.sh
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    - https://webhook-staging.atomist.services/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - "$HOME/.atomist"
